version: '3'
services:
  db:
    image: postgres
    container_name: database-rails-graphql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rails_graphql_network

  api:
    platform: linux/x86_64
    container_name: rails-graphql
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/rails-graphql"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ${MASTER_KEY}
    networks:
      - rails_graphql_network

  redis:
    image: redis:alpine
    container_name: redis-rails-graphql
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks:
      - rails_graphql_network

volumes:
  pgdata:
  redisdata:

networks:
  rails_graphql_network:

